web/healthapps/models.py
"""
Database models for the application.
"""
# Imports
from datetime import datetime
from app import db


# Model - Health App
class HealthApp(db.Model):
    """Third-party Health App model"""

    __tablename__ = "health_apps"

    # IDs
    id = db.Column(db.Integer, primary_key=True)
    # Web Scraping Source
    source = db.Column(db.Text, nullable=False)
    # App Information
    name = db.Column(db.Text, nullable=False)
    company = db.Column(db.Text, nullable=False)
    description = db.Column(db.Text, nullable=False)
    link = db.Column(db.Text, nullable=False)
    # Timestamps
    created_date = db.Column(db.DateTime, nullable=False,
                             default=datetime.utcnow)
    updated_date = db.Column(db.DateTime)
    # Updatestamps
    created_by = db.Column(db.Integer, db.ForeignKey("users.id"))
    updated_by = db.Column(db.Integer, db.ForeignKey("users.id"))

web/healthapps/views.py
"""Health Apps > Views"""
# Imports
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required
from models.healthapps_models import HealthApp
from utils.app_scraping_CARIN import (
    scrape_carin_health_apps_and_store,
)
from utils.app_scraping_api_MedicareBlueButton import (
    scrape_medicare_api_health_apps,
)


# Blueprint Configuration
healthapps_bp = Blueprint('healthapps', __name__)


# Route - Health Apps
@healthapps_bp.route('/healthapps')
@login_required
def healthapps():
    """Health Apps page"""
    healthapps_list = HealthApp.query.all()
    return render_template('healthapps/healthapps.html',
                           title='Health Apps',
                           healthapps_list=healthapps_list)


# Function - CARIN Scraper
@healthapps_bp.route('/healthapps/scrape_carin', methods=['POST'])
@login_required
def scrape_carin():
    """Scrape and store health apps from CARIN website"""

    try:
        scrape_carin_health_apps_and_store()
        flash('CARIN health apps successfully scraped and stored.',
              'success')
    except Exception as error:
        flash(f'Error scraping CARIN health apps. {error}', 'error')

    return redirect(url_for('healthapps.healthapps'))


# Function - Medicare Blue Button Scraper
@healthapps_bp.route('/healthapps/scrape_medicare', methods=['POST'])
@login_required
def scrape_medicare():
    """Scrape and store health apps from Medicare website"""

    try:
        scrape_medicare_api_health_apps()
        flash(
            'Medicare Blue Button health apps successfully stored.',
            'success'
        )
    except Exception as error:
        flash(
            f'Error scraping Medicare Blue Button health apps. {error}',
            'error'
        )

    return redirect(url_for('healthapps.healthapps'))

web/views/healthapps_views.py
"""Health Apps > Views"""
# Imports
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required
from models.healthapps_models import HealthApp
from utils.app_scraping_CARIN import (
    scrape_carin_health_apps_and_store,
)
from utils.app_scraping_api_MedicareBlueButton import (
    scrape_medicare_api_health_apps,
)


# Blueprint Configuration
healthapps_bp = Blueprint('healthapps', __name__)


# Route - Health Apps
@healthapps_bp.route('/healthapps')
@login_required
def healthapps():
    """Health Apps page"""
    healthapps_list = HealthApp.query.all()
    return render_template('healthapps/healthapps.html',
                           title='Health Apps',
                           healthapps_list=healthapps_list)


# Function - CARIN Scraper
@healthapps_bp.route('/healthapps/scrape_carin', methods=['POST'])
@login_required
def scrape_carin():
    """Scrape and store health apps from CARIN website"""

    try:
        scrape_carin_health_apps_and_store()
        flash('CARIN health apps successfully scraped and stored.',
              'success')
    except Exception as error:
        flash(f'Error scraping CARIN health apps. {error}', 'error')

    return redirect(url_for('healthapps.healthapps'))


# Function - Medicare Blue Button Scraper
@healthapps_bp.route('/healthapps/scrape_medicare', methods=['POST'])
@login_required
def scrape_medicare():
    """Scrape and store health apps from Medicare website"""

    try:
        scrape_medicare_api_health_apps()
        flash(
            'Medicare Blue Button health apps successfully stored.',
            'success'
        )
    except Exception as error:
        flash(
            f'Error scraping Medicare Blue Button health apps. {error}',
            'error'
        )

    return redirect(url_for('healthapps.healthapps'))

web/templates/healthapps/healthapps.html
{% extends 'base.html' %} {% block content %}
<h1>Health Apps</h1>
<!-- Health Apps - Force Scraping - Start -->
<div class="button-group">
  <form action="{{ url_for('healthapps.scrape_carin') }}" method="post">
    <input type="submit" value="Update CARIN" class="btn btn-primary" />
  </form>
  <form action="{{ url_for('healthapps.scrape_medicare') }}" method="post">
    <input type="submit" value="Update Medicare BB" class="btn btn-primary" />
  </form>
</div>
<!-- Health Apps - Force Scraping - End -->
<!-- Health Apps - Start -->
<div class="row mb-3">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Source</th>
        <th>App Name</th>
        <th>Company</th>
        <th>Created Date</th>
        <th>Source Updated Date</th>
      </tr>
    </thead>
    <tbody>
      {% if healthapps_list %} {% for app in healthapps_list %}
      <tr>
        <td>{{ app.source }}</td>
        <td>
          <a href="{{ app.link }}" target="_blank">{{ app.name }}</a>
        </td>
        <td>{{ app.company }}</td>
        <td
          class="timestamp"
          data-utc="{{ app.created_date.isoformat() }}Z"
        ></td>
        {% if app.updated_date %}
        <td
          class="timestamp"
          data-utc="{{ app.updated_date.isoformat() }}Z"
        ></td>
        {% else %}
        <td></td>
        {% endif %}
      </tr>
      {% endfor %} {% else %}
      <!-- If no apps found, extend all 6 columns -->
      <tr>
        <td colspan="6">No apps found</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
</div>
<!-- Health Apps - End -->
<script src=" {{ url_for('static', filename='js/convert_timezone.js') }}"></script>
{% endblock content %}