web/core/views.py
"""Core > Views"""
# Imports
from flask import render_template, Blueprint


# Blueprint
core_bp = Blueprint('core', __name__)


# Home page
@core_bp.route('/')
def index():
    """Home page"""

    return render_template('core/index.html',
                           title='H3O Inferno - Home')

web/reports/views.py
"""
Reports > views.py
Routes and functions to generate and view reports.
"""
# Imports
import io
import csv
from datetime import datetime
from flask import Blueprint, request, render_template, make_response
from flask_login import login_required, current_user
from forms.reports_forms import GenerateReportForm
from .sql_queries import (
    get_report_connect_requests_active,
    get_report_connect_requests_new,
    get_report_connect_requests_approved,
    get_report_connect_requests_denied,
    get_report_connect_requests_all,
    get_report_connect_requests_change_log,
    get_report_health_apps,
    get_report_inferno_users,
)


# Blueprint Configuration
reports_bp = Blueprint("reports", __name__)


# Reports
@reports_bp.route("/reports", methods=["GET", "POST"])
@login_required
def generate_report():
    """Route for generating and viewing reports."""

    form = GenerateReportForm()

    # Report Options
    # Make sure to update the following functions:
    # - get_column_labels()
    # - generate_report_data()
    form.report_options.choices = [
        ("Connection Requests - Active", "Connection Requests - Active"),
        ("Connection Requests - New", "Connection Requests - New"),
        ("Connection Requests - Approved", "Connection Requests - Approved"),
        ("Connection Requests - Denied", "Connection Requests - Denied"),
        ("Connection Requests - All", "Connection Requests - All"),
        ("Connection Requests - Change Log",
         "Connection Requests - Change Log"),
        ("Health Apps", "Health Apps"),
        ("Inferno Users", "Inferno Users"),
    ]

    if request.method == "POST":
        # Get the selected report and date parameters from the form
        selected_report = form.report_options.data
        start_date = form.start_date.data
        end_date = form.end_date.data

        # Generate report data based on the selected report and date parameters
        report_data = generate_report_data(
            selected_report, start_date, end_date)

        # Define custom column labels based on the selected report
        column_labels = get_column_labels(selected_report)
        # Count of the columns for the selected report
        column_count = len(column_labels)

        # Render the report template with the generated data
        return render_template(
            "reports/report.html",
            title="Soulstone - Report",
            user=current_user,
            report_data=report_data,
            selected_report=selected_report,
            start_date=start_date,
            end_date=end_date,
            column_labels=column_labels,
            column_count=column_count,
        )

    return render_template(
        "reports/generate_report.html",
        title="Soulstone - Generate Report",
        form=form,
        user=current_user,
    )


@reports_bp.route("/reports/export-csv", methods=["POST"])
@login_required
def export_csv():
    """Route for exporting report data as CSV."""

    # Current Time
    current_time = datetime.utcnow()

    # Get the selected report and date parameters from the form
    selected_report = request.form.get("selected_report")
    start_date = request.form.get("start_date")
    end_date = request.form.get("end_date")

    # Generate report data based on the selected report and date parameters
    report_data = generate_report_data(selected_report, start_date, end_date)

    # Define custom column labels based on the selected report
    column_labels = get_column_labels(selected_report)

    # Generate a CSV file in memory
    csv_output = generate_csv(report_data, column_labels)

    # Create a response with the CSV file
    response = make_response(csv_output.getvalue())

    # Set the appropriate headers for CSV download
    response.headers[
        "Content-Disposition"
    ] = f"attachment; filename={selected_report}_{current_time}.csv"
    response.headers["Content-type"] = "text/csv"

    return response


def generate_csv(data, column_labels):
    """Generate a CSV file from the provided data and column labels."""
    output = io.StringIO()
    writer = csv.writer(output)

    # Write the header row
    writer.writerow(column_labels)

    # Write the data rows
    for row in data:
        writer.writerow(row)

    return output


def get_column_labels(report):
    """Get custom column labels based on the selected report."""

    # Connection Requests - Column Labels
    if report == "Connection Requests - Active" \
            or report == "Connection Requests - New" \
            or report == "Connection Requests - Approved" \
            or report == "Connection Requests - Denied" \
            or report == "Connection Requests - All":
        return [
            "ID",
            "Health Plan Name",
            "First Name",
            "Last Name",
            "Email",
            "Phone Number",
            "Company",
            "Company Website",
            "App Name",
            "App Link",
            "App Type Web",
            "App Type Mobile",
            "App Type Native",
            "App Type Other",
            "App Description",
            "CARIN Link",
            "Medicare Link",
            "CAQH Link",
            "FHIR Patient Access API",
            "FHIR Provider Directory API",
            "FHIR Drug Formulary API",
            "Working Status",
            "Created Date",
            "Created By",
            "Updated Date",
            "Updated By",
        ]
    # Connection Requests - Change Log - Column Labels
    elif report == "Connection Requests - Change Log":
        return [
            "Connection Request ID",
            "Health Plan Name",
            "Request App Name",
            "Chagned From Working Status",
            "Changed To Working Status",
            "Changed Date",
            "Changed By",
        ]
    # Health Apps - Column Labels
    elif report == "Health Apps":
        return [
            "ID",
            "Source",
            "Name",
            "Company",
            "Description",
            "Link",
            "Created Date",
            "Created By",
            "Updated Date",
            "Updated By",
        ]
    # Inferno Users - Column Labels
    elif report == "Inferno Users":
        return [
            "ID",
            "Email",
            "Status",
            "Created Date",
        ]
    else:
        # Handle other report options if needed
        return []


def generate_report_data(report, start_date, end_date):
    """
    Generate report data based on the selected report
    and date parameters.
    """

    # Connection Requests - Active
    if report == "Connection Requests - Active":
        return get_report_connect_requests_active(start_date, end_date)
    # Connection Requests - New
    elif report == "Connection Requests - New":
        return get_report_connect_requests_new(start_date, end_date)
    # Connection Requests - Approved
    elif report == "Connection Requests - Approved":
        return get_report_connect_requests_approved(start_date, end_date)
    # Connection Requests - Denied
    elif report == "Connection Requests - Denied":
        return get_report_connect_requests_denied(start_date, end_date)
    # Connection Requests - All
    elif report == "Connection Requests - All":
        return get_report_connect_requests_all(start_date, end_date)
    # Connection Requests - Change Log
    elif report == "Connection Requests - Change Log":
        return get_report_connect_requests_change_log(start_date, end_date)
    # Health Apps
    elif report == "Health Apps":
        return get_report_health_apps(start_date, end_date)
    # Inferno Users
    elif report == "Inferno Users":
        return get_report_inferno_users(start_date, end_date)
    else:
        # Handle other report options if needed
        return []

web/users/views.py
"""Users > Views"""
# Imports
from random import randint
from flask import (
    Blueprint, abort, render_template, request, flash, redirect, url_for,
    session,
)
from werkzeug.security import generate_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from forms.users_forms import (
    RegisterUserForm, LoginForm, ChangePasswordForm, ShortCodeForm,
)
from flask_mail import Message
from app import db, mail
from models.users_models import User


# Blueprint Configuration
users_bp = Blueprint('users', __name__)


# Register User
@users_bp.route('/register', methods=['GET', 'POST'])
def register_user():
    """Registers a new user"""

    form = RegisterUserForm()

    if form.validate_on_submit():
        # Check if email is already registered
        if User.query.filter_by(email=form.email.data).first():
            flash('This email is already registered.', 'error')
            return redirect(url_for('users.login'))

        # If the email does not end with @healthtrio or @mpulse, make user
        if not form.email.data.endswith('@healthtrio.com') and not form.email.data.endswith('@mpulse.com'):
            # Commit the new user to the database
            user = User(
                email=form.email.data,
                password_hash=generate_password_hash(form.password.data),
                user_type=form.user_type.data
            )
            db.session.add(user)
            db.session.commit()
            flash('You have successfully registered!', 'success')
            return redirect(url_for('users.login'))

        # If the email ends with @healthtrio or @mpulse, make admin
        user = User(
            email=form.email.data,
            password_hash=generate_password_hash(form.password.data),
            role='admin'
        )
        db.session.add(user)
        db.session.commit()
        flash('You have successfully registered!', 'success')
        return redirect(url_for('users.login'))

    return render_template('users/register.html',
                           title='H3O Inferno - Register',
                           form=form)


# Route - Login and send Short Code (2FA)
@users_bp.route('/login', methods=['GET', 'POST'])
def login():
    """Logs in a user and sends a short code (2FA) to their email"""

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            # Check user's status
            if user.status == 'INACTIVE':
                flash(
                    """Your account is inactive.
                    Please contact an administrator.""",
                    'error')
                return redirect(url_for('users.login'))

            # Generate a short code to complete the login process
            short_code = str(randint(100000, 999999))

            # Send the short code to the user's email
            msg = Message('H3O Inferno - Short Code for Login',
                          recipients=[user.email],
                          sender="noreply-2FA@healthtrio.com")
            msg.body = f'Your short code is: {short_code}'
            mail.send(msg)

            # Store the short code in the session
            session['short_code'] = short_code
            # After generating the short code and sending the email
            session['user_id'] = user.id

            # Redirect the user to the short code page
            return redirect(url_for('users.enter_code'))

        flash('Invalid email or password.', 'error')

    return render_template('users/login.html',
                           title='H3O Inferno - Login',
                           form=form)


# Route - Enter Short Code (2FA)
@users_bp.route('/short_code', methods=['GET', 'POST'])
def enter_code():
    """Validates the short code (2FA) and completes the login process"""

    form = ShortCodeForm()

    if form.validate_on_submit():
        # Variables
        entered_code = form.short_code.data
        stored_code = session.get('short_code')

        # Check if the entered code matches the stored code
        if entered_code == stored_code:
            flash('Short Code (2FA) is correct. Completing login.', 'success')
            return redirect(url_for('users.complete_login'))
        else:
            flash('Short Code (2FA) is incorrect. Please try again.', 'error')

    return render_template('users/short_code.html',
                           title='H3O Inferno - Short Code (2FA)',
                           form=form)


# Route - Complete Login
@users_bp.route('/complete_login')
def complete_login():
    """Completes the login process if the short code (2FA) is correct"""

    # Variables
    stored_user_id = session.get('user_id')
    user = User.query.get_or_404(stored_user_id)

    # Log the user in
    if user:
        login_user(user)
        session.pop('short_code', None)

        next = request.args.get('next')

        if next is None or not next[0] == '/':
            next = url_for('core.index')

        flash('Login successful.', 'success')
        return redirect(next)

    # If the user is not found, redirect to the login page
    flash('Login failed.', 'error')
    return redirect(url_for('users.login'))


# Logout user
@users_bp.route('/logout')
@login_required
def logout():
    '''Logs out a user'''

    logout_user()
    return redirect(url_for('core.index'))


# Route - User Account
@users_bp.route('/account/<int:user_id>', methods=['GET', 'POST'])
@login_required
def user_profile(user_id):
    """Routes the current user to their profile page"""

    user = User.query.get_or_404(user_id)

    if user != current_user:
        abort(403)

    return render_template('users/account.html',
                           title='H3O Inferno - Account',
                           user=user)


# Route - Change Password
@users_bp.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    """Allows the user to change their password"""

    user = User.query.get_or_404(current_user.id)

    if user != current_user:
        abort(403)

    form = ChangePasswordForm()

    if form.validate_on_submit():
        user.password_hash = generate_password_hash(form.password.data)
        db.session.commit()
        flash('Your password has been updated.', 'success')
        return redirect(url_for('users.user_profile', user_id=user.id))

    return render_template('users/change_password.html',
                           title='H3O Inferno - Change Password',
                           form=form)

web/templates/base.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }}</title>
    {% include 'favicon.html' %} {% include 'styles.html' %}
  </head>
  <body>
    <div class="container">
      <!-- Navbar - Start -->
      {% include 'navigation.html' %}
      <!-- Navbar - End -->
      <main>
        <!-- Flash - Start -->
        {% include 'flash.html' %}
        <!-- Flash - End -->
        {% block content %}{% endblock content %}
      </main>
    </div>
    {% include 'javascript.html' %}
  </body>
</html>

web/templates/favicon.html
<link
  rel="apple-touch-icon"
  sizes="180x180"
  href="{{ url_for('static', filename='assets/favicons/apple-touch-icon.png') }}"
/>
<link
  rel="icon"
  type="image/png"
  sizes="32x32"
  href="{{ url_for('static', filename='assets/favicons/favicon-32x32.png') }}"
/>
<link
  rel="icon"
  type="image/png"
  sizes="16x16"
  href="{{ url_for('static', filename='assets/favicons/favicon-16x16.png') }}"
/>
<link
  rel="manifest"
  href="{{ url_for('static', filename='assets/favicons/site.webmanifest') }}"
/>
<link
  rel="mask-icon"
  href="{{ url_for('static', filename='assets/favicons/safari-pinned-tab.svg') }}"
  color="#5bbad5"
/>
<meta name="msapplication-TileColor" content="#da532c" />
<meta name="theme-color" content="#ffffff" />

web/templates/flash.html
{% with messages=get_flashed_messages(with_categories=true) %} {% if messages %}
{% for category, message in messages %}
<div class="row">
  <div class="banner-container">
    <div class="banner {{ category }}">
      <span class="banner-text">{{ message }}</span>
      <button class="banner-close" onclick="hideBanner()">&times;</button>
    </div>
  </div>
</div>
{% endfor %} {% endif %} {% endwith %}

web/templates/javascript.html
<!-- JS - Start -->
<!-- jQuery -->
<script src="{{ url_for('static', filename='jquery/jquery.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.js') }}"></script>
<!-- FontAwesome -->
<script src="{{ url_for('static', filename='fontawesome/js/all.min.js') }}"></script>
<!-- Custom -->
<script src="{{ url_for('static', filename='js/main.js') }}" /></script>
<!-- JS - End -->

web/templates/navigation.html
{% block navbar %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('core.index') }}">
      <img
        src="{{ url_for('static', filename='assets/logo/h3o-inferno-logo-329x569.png') }}"
        alt="Logo"
        width="24"
        height="30"
        class="d-inline-block align-text-top"
      />
      H3O Inferno
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('core.index') }}"
            ><i class="fas fa-home"></i> Home</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="{{ url_for('requests.connection_request') }}"
            ><i class="fas fa-file-circle-plus"></i> Request</a
          >
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('requests.view_requests') }}"
            ><i class="fas fa-file-circle-check"></i> View Requests</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('healthapps.healthapps') }}"
            ><i class="fas fa-box"></i> Health Apps</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('reports.generate_report') }}"
            ><i class="fas fa-chart-simple"></i> Reports</a
          >
        </li>
        {% endif %}
      </ul>
      <span class="navbar-text">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('settings.settings') }}"
              ><i class="fas fa-cog"></i> Settings</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              href="{{ url_for('users.user_profile', user_id=current_user.id) }}"
              ><i class="fas fa-user"></i> Profile</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.logout') }}"
              ><i class="fas fa-sign-out-alt"></i> Logout</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.register_user') }}"
              ><i class="fas fa-arrow-right"></i> Register</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.login') }}"
              ><i class="fas fa-sign-in-alt"></i> Login</a
            >
          </li>
          {% endif %}
        </ul>
      </span>
    </div>
  </div>
</nav>
{% endblock navbar %}

web/templates/styles.html
<!-- Fonts - Start -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
  rel="stylesheet"
/>
<!-- Fonts - End -->
<!-- CSS  Start -->
<!-- Bootstrap -->
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}"
/>
<!-- FontAwesome -->
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='fontawesome/css/fontawesome.min.css') }}"
/>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='fontawesome/css/all.min.css') }}"
/>
<!-- CSS - End -->