web/request/views.py
"""Requests > Views"""
# Imports
import pdfkit
from datetime import datetime
from flask import (
    Blueprint, render_template, request, flash, redirect, url_for, jsonify,
    make_response,
)
from flask_login import login_required, current_user
from forms.requests_forms import (
    ConnectionRequestForm, RequestWorkingStatusForm, JiraTicketsForm,
)
from app import db
from settings.settings_models import HealthPlan
from models.request_models import (
    ConnectionRequest, RequestJira, ConnectionRequestChangeLog
)
from request.sql_queries import (
    get_all_connection_requests, get_all_connection_requests_count,
    get_connection_request,
)
from utils.app_match import calculate_affiliate_match_probability


# Blueprint Configuration
requests_bp = Blueprint("requests", __name__)


# Route - Connection Request
@requests_bp.route("/connection_request", methods=["GET", "POST"])
def connection_request():
    """Form for connection request. This is an unauthenticated route."""

    form = ConnectionRequestForm()

    # Populate the Health Plan ID dropdown
    form.health_plan_id.choices = [
        (health_plan.id, f"{health_plan.name} ({health_plan.hp_id})")
        for health_plan in db.session.query(
            HealthPlan.id, HealthPlan.name, HealthPlan.hp_id,
        ).filter(
            HealthPlan.status == "ACTIVE"
        ).order_by(
            HealthPlan.name.asc()
        ).all()]

    if form.validate_on_submit():
        new_request = ConnectionRequest(
            firstname=form.firstname.data,
            lastname=form.lastname.data,
            email=form.email.data,
            phone_number=form.phone_number.data,
            company=form.company.data,
            company_website=form.company_website.data,
            app_name=form.app_name.data,
            app_link=form.app_link.data,
            app_type_web=form.app_type_web.data,
            app_type_mobile=form.app_type_mobile.data,
            app_type_native=form.app_type_native.data,
            app_type_other=form.app_type_other.data,
            app_description=form.app_description.data,
            carin_link=form.carin_link.data,
            medicare_link=form.medicare_link.data,
            caqh_link=form.caqh_link.data,
            fhir_patient_access_api=form.fhir_patient_access_api.data,
            fhir_provider_directory_api=form.fhir_provider_directory_api.data,
            fhir_drug_formulary_api=form.fhir_drug_formulary_api.data,
            health_plan_id=form.health_plan_id.data,
        )
        db.session.add(new_request)
        db.session.commit()
        flash("Your request has been submitted. We will be in touch soon.",
              "success")
        return redirect(url_for("core.index"))

    return render_template("requests/connection_request.html",
                           title="Connection Request",
                           form=form)


# Route - View All Requests
@requests_bp.route("/view_requests", methods=["GET", "POST"])
@login_required
def view_requests():
    """View all requests. This is an authenticated route."""

    requests = get_all_connection_requests()
    count = get_all_connection_requests_count()

    return render_template("requests/view_requests.html",
                           title="View Requests",
                           requests=requests,
                           count=count)


# Route - View Request
@requests_bp.route("/view_request/<int:request_id>")
@login_required
def view_request(request_id):
    """View a request. This is an authenticated route."""

    connection_request = get_connection_request(request_id)

    return render_template("requests/view_request.html",
                           title="View Request",
                           connection_request=connection_request)


# Route - Edit Request
@requests_bp.route("/edit_request/<int:request_id>", methods=["GET", "POST"])
@login_required
def edit_request(request_id):
    """Edit a request. This is an authenticated route."""

    form = ConnectionRequestForm()

    connection_request = ConnectionRequest.query.get_or_404(request_id)

    # Populate the Health Plan ID dropdown
    form.health_plan_id.choices = [
        (health_plan.id, f"{health_plan.name} ({health_plan.hp_id})")
        for health_plan in db.session.query(
            HealthPlan.id, HealthPlan.name, HealthPlan.hp_id,
        ).filter(
            HealthPlan.status == "ACTIVE"
        ).order_by(
            HealthPlan.name.asc()
        ).all()]

    # Populate form fields with existing data
    if request.method == "GET":
        form.firstname.data = connection_request.firstname
        form.lastname.data = connection_request.lastname
        form.email.data = connection_request.email
        form.phone_number.data = connection_request.phone_number
        form.company.data = connection_request.company
        form.company_website.data = connection_request.company_website
        form.app_name.data = connection_request.app_name
        form.app_link.data = connection_request.app_link
        form.app_type_web.data = connection_request.app_type_web
        form.app_type_mobile.data = connection_request.app_type_mobile
        form.app_type_native.data = connection_request.app_type_native
        form.app_type_other.data = connection_request.app_type_other
        form.app_description.data = connection_request.app_description
        form.carin_link.data = connection_request.carin_link
        form.medicare_link.data = connection_request.medicare_link
        form.caqh_link.data = connection_request.caqh_link
        form.fhir_patient_access_api.data = \
            connection_request.fhir_patient_access_api
        form.fhir_provider_directory_api.data = \
            connection_request.fhir_provider_directory_api
        form.fhir_drug_formulary_api.data = \
            connection_request.fhir_drug_formulary_api
        form.health_plan_id.data = connection_request.health_plan_id

    if form.validate_on_submit():
        connection_request.firstname = form.firstname.data
        connection_request.lastname = form.lastname.data
        connection_request.email = form.email.data
        connection_request.phone_number = form.phone_number.data
        connection_request.company = form.company.data
        connection_request.company_website = form.company_website.data
        connection_request.app_name = form.app_name.data
        connection_request.app_link = form.app_link.data
        connection_request.app_type_web = form.app_type_web.data
        connection_request.app_type_mobile = form.app_type_mobile.data
        connection_request.app_type_native = form.app_type_native.data
        connection_request.app_type_other = form.app_type_other.data
        connection_request.app_description = form.app_description.data
        connection_request.carin_link = form.carin_link.data
        connection_request.medicare_link = form.medicare_link.data
        connection_request.caqh_link = form.caqh_link.data
        connection_request.fhir_patient_access_api = \
            form.fhir_patient_access_api.data
        connection_request.fhir_provider_directory_api = \
            form.fhir_provider_directory_api.data
        connection_request.fhir_drug_formulary_api = \
            form.fhir_drug_formulary_api.data
        connection_request.health_plan_id = form.health_plan_id.data
        connection_request.updated_date = datetime.utcnow()
        connection_request.updated_by = current_user.id
        db.session.commit()
        flash("Connection request has been updated.", "success")
        return redirect(url_for("requests.view_request",
                                request_id=request_id))

    return render_template("requests/connection_request.html",
                           title="Edit Request",
                           form=form,
                           connection_request=connection_request)


# Route - Status Updates
@requests_bp.route("/status_updates/<int:request_id>", methods=["GET", "POST"])
@login_required
def status_updates(request_id):
    """Allows the HealthTrio user to update the status of a request."""

    form = RequestWorkingStatusForm()

    connection_request = ConnectionRequest.query.get_or_404(request_id)

    # Populate form fields with existing data
    if request.method == "GET":
        form.working_status.data = connection_request.working_status

    # Update the status of the request
    if form.validate_on_submit():
        # Create a new change log record
        new_change_log = ConnectionRequestChangeLog(
            connectionrequest_id=request_id,
            previous_working_status=connection_request.working_status,
            changed_working_status=form.working_status.data,
            changed_date=datetime.utcnow(),
            changed_by=current_user.id,
        )
        db.session.add(new_change_log)
        db.session.commit()

        # Update the status of the request
        connection_request.working_status = form.working_status.data
        connection_request.updated_date = datetime.utcnow()
        connection_request.updated_by = current_user.id
        db.session.commit()

        flash("Status has been updated.", "success")
        return redirect(url_for("requests.view_request",
                                request_id=request_id))

    return render_template("requests/status_updates.html",
                           title="Status Updates",
                           form=form,
                           connection_request=connection_request)


# Route - Jira Ticket Updates
@requests_bp.route("/jira_ticket_updates/<int:request_id>",
                   methods=["GET", "POST"])
@login_required
def jira_ticket_updates(request_id):
    """Allows the HealthTrio user to update the Jira ticket of a request."""

    form = JiraTicketsForm()

    connection_request = ConnectionRequest.query.get_or_404(request_id)
    jira_tickets = RequestJira.query.filter_by(

web/settings/views.py
"""
Settings > views.py
Routes and functions to manage application settings.
"""
# Imports
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required
from forms.settings_forms import ChangeRoleForm, ChangeStatusForm, HealthPlanForm
from decorators.decorators import admin_required
from sqlalchemy import or_
from app import db
from models.settings_models import HealthPlan
from models.users_models import User


# Blueprint Configuration
settings_bp = Blueprint('settings', __name__)


# Route - Settings Landing Page
@settings_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    """Settings landing page"""

    return render_template('settings/settings.html',
                           title='Settings')


# Route - Settings > Manage Users
@settings_bp.route('/settings/manage-users',
                   methods=['GET', 'POST'])
@admin_required
@login_required
def manage_users():
    """Manage users page"""

    users = User.query.all()

    return render_template('settings/manage-users.html',
                           title='Manage Users',
                           users=users)


# Route - Settings > Manage Users > Change Role
@settings_bp.route('/settings/manage-users/change-role/<int:user_id>',
                   methods=['GET', 'POST'])
@admin_required
@login_required
def change_role(user_id):
    """Change user role page"""

    user = User.query.get_or_404(user_id)

    form = ChangeRoleForm()

    if request.method == 'GET':
        form.role.data = user.role

    if form.validate_on_submit():
        user.role = form.role.data
        db.session.commit()

        return redirect(url_for('settings.manage_users'))

    return render_template('settings/change-role.html',
                           title='Change Role',
                           form=form,
                           user=user)


# Route - Settings > Manage Users > Change Status
@settings_bp.route('/settings/manage-users/change-status/<int:user_id>',
                   methods=['GET', 'POST'])
@admin_required
@login_required
def change_status(user_id):
    """Change user status page"""

    user = User.query.get_or_404(user_id)

    form = ChangeStatusForm()

    if request.method == 'GET':
        form.status.data = user.status

    if form.validate_on_submit():
        user.status = form.status.data
        db.session.commit()

        return redirect(url_for('settings.manage_users'))

    return render_template('settings/change-status.html',
                           title='Change Status',
                           form=form,
                           user=user)


# Settings - Manage Health Plans
@settings_bp.route('/settings/manage-health-plans',
                   methods=['GET', 'POST'])
@login_required
def manage_health_plans():
    """Manage health plans page"""

    health_plans = HealthPlan.query.all()

    return render_template('settings/manage-health-plans.html',
                           title='Manage Health Plans',
                           health_plans=health_plans)


# Settings - Manage Health Plans > Add Health Plan
@settings_bp.route('/settings/manage-health-plans/add-health-plan',
                   methods=['GET', 'POST'])
@login_required
def add_health_plan():
    """Add health plan page"""

    form = HealthPlanForm()

    if form.validate_on_submit():
        # Check if health plan already exists via name or health plan ID
        health_plan = HealthPlan.query.filter(
            or_(HealthPlan.name == form.name.data,
                HealthPlan.hp_id == form.hp_id.data)).first()
        if health_plan:
            flash('Health plan already exists.', 'danger')

        # Add to the database
        health_plan = HealthPlan(
            name=form.name.data,
            hp_id=form.hp_id.data,
            status=form.status.data,)
        db.session.add(health_plan)
        db.session.commit()

        flash('Health Plan added successfully.', 'success')
        return redirect(url_for('settings.manage_health_plans'))

    return render_template('settings/add-edit-health-plan.html',
                           title='Add Health Plan',
                           form=form)


# Settings - Manage Health Plans > Edit Health Plan
@settings_bp.route(
    '/settings/manage-health-plans/edit-health-plan/<int:health_plan_id>',
    methods=['GET', 'POST'])
@login_required
def edit_health_plan(health_plan_id):
    """Edit health plan page"""

    health_plan = HealthPlan.query.get_or_404(health_plan_id)

    form = HealthPlanForm()

    if request.method == 'GET':
        form.name.data = health_plan.name
        form.hp_id.data = health_plan.hp_id
        form.status.data = health_plan.status

    if form.validate_on_submit():
        # Update the database
        health_plan.name = form.name.data
        health_plan.hp_id = form.hp_id.data
        health_plan.status = form.status.data
        db.session.commit()

        flash('Health Plan updated successfully.', 'success')
        return redirect(url_for('settings.manage_health_plans'))

    return render_template('settings/add-edit-health-plan.html',
                           title='Edit Health Plan',
                           form=form,
                           health_plan=health_plan)

web/templates/requests/connection_request.html
{% extends 'base.html' %} {% block content %}
<h1>Connection Request</h1>
<div id="request_form">
  <p>
    Please tell us about yourself and the application you wish to connect to our
    FHIR APIs.
  </p>
  <form action="" method="post">
    {{ form.hidden_tag() }} {% if current_user.is_authenticated %}
    <div class="row">
      <h4>Tell us about which health plan you're requestion from</h4>
      <div class="u-full-width">
        {{ form.health_plan_id.label }} {{ form.health_plan_id }}
        <p>
          Can't find the Health Plan?
          <a href="{{ url_for('settings.add_health_plan') }}"
            >Create a new Health Plan here.</a
          >
        </p>
      </div>
    </div>
    {% else %}
    <div class="row" hidden>
      <h4>Tell us about which health plan you're requestion from</h4>
      <div class="u-full-width">
        {{ form.health_plan_id.label }} {{ form.health_plan_id }}
      </div>
    </div>
    {% endif %}
    <h4>Tell us about yourself and your company</h4>
    <div class="row">
      <div class="one-half column">
        {{ form.firstname.label }} {{ form.firstname }}
      </div>
      <div class="one-half column">
        {{ form.lastname.label }} {{ form.lastname }}
      </div>
    </div>
    <div class="row">
      <div class="one-half column">{{ form.email.label }} {{ form.email }}</div>
      <div class="one-half column">
        {{ form.phone_number.label }} {{ form.phone_number }}
      </div>
    </div>
    <div class="row">
      <div class="one-half column">
        {{ form.company.label }} {{ form.company }}
      </div>
      <div class="one-half column">
        {{ form.company_website.label }} {{ form.company_website }}
      </div>
    </div>
    <div class="row">
      <h4>Tell us about your app</h4>
      <div class="u-full-width">
        {{ form.app_name.label }} {{ form.app_name }}
      </div>
    </div>
    <h4>App Type</h4>
    <div class="row">
      <div class="three columns checkbox-group">
        {{ form.app_type_web(class="checkbox-input") }} {{
        form.app_type_web.label }}
      </div>
      <div class="three columns checkbox-group">
        {{ form.app_type_mobile(class="checkbox-input") }} {{
        form.app_type_mobile.label }}
      </div>
      <div class="three columns checkbox-group">
        {{ form.app_type_native(class="checkbox-input") }} {{
        form.app_type_native.label }}
      </div>
      <div class="three columns checkbox-group">
        {{ form.app_type_other(class="checkbox-input") }} {{
        form.app_type_other.label }}
      </div>
    </div>
    <div class="row">
      <div class="u-full-width">
        {{ form.app_link.label }} {{ form.app_link }}
      </div>
    </div>
    <div class="row">
      <div class="u-full-width">
        {{ form.app_description.label }} {{ form.app_description }}
      </div>
    </div>
    <div class="row">
      <h4>Links to authorized health apps</h4>
      <div class="u-full-width">
        {{ form.carin_link.label }} {{ form.carin_link }}
      </div>
      <div class="u-full-width">
        {{ form.medicare_link.label }} {{ form.medicare_link }}
      </div>
      <div class="u-full-width">
        {{ form.caqh_link.label }} {{ form.caqh_link }}
      </div>
    </div>
    <h4>Tell us which API(s) you want to connect to</h4>
    <div class="row">
      <div class="four columns checkbox-group">
        {{ form.fhir_patient_access_api(class="checkbox-input") }} {{
        form.fhir_patient_access_api.label }}
      </div>
      <div class="four columns checkbox-group">
        {{ form.fhir_provider_directory_api(class="checkbox-input") }} {{
        form.fhir_provider_directory_api.label }}
      </div>
      <div class="four columns checkbox-group">
        {{ form.fhir_drug_formulary_api(class="checkbox-input") }} {{
        form.fhir_drug_formulary_api.label }}
      </div>
    </div>
    <div class="row">
      <div>{{ form.submit }}</div>
    </div>
  </form>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    // Extract the health_plan_id from the URL
    const urlParams = new URLSearchParams(window.location.search);
    const healthPlanId = urlParams.get("health_plan_id");

    // Select the dropdown element
    const healthPlanDropdown = document.getElementById("health_plan_id");

    // Get the existing options in the dropdown
    const existingOptions = healthPlanDropdown.options;

    {% if current_user.is_authenticated %}
    // If the user is logged in, ignore the healthPlanId from the URL
    // and make the dropdown selection null
    healthPlanDropdown.value = null;
    {% else %}
    // Check if the healthPlanId matches an existing option
    let matchFound = false;
    for (let i = 0; i < existingOptions.length; i++) {
      if (existingOptions[i].value === healthPlanId) {
        // If a match is found, select that option and exit the loop
        healthPlanDropdown.value = healthPlanId;
        matchFound = true;
        break;
      }
    }

    // If no match is found, display the "Unfortunately" paragraph
    if (!matchFound) {
      const requestForm = document.getElementById("request_form");
      requestForm.innerHTML =
        "<p>Unfortunately, we can't process your request at this time. Please reach out to your health plan to get the correct URL to request access to their FHIR APIs.</p>";
    }
    {% endif %}
  });
</script>
{% endblock content %}

web/templates/requests/jira_ticket_updates.html
{% extends 'base.html' %} {% block content %}
<h1>Jira Ticket Updates</h1>
<p>Add or update the Jira CC and CSM1 IDs and URLs below.</p>
<form method="post">
  {{ form.hidden_tag() }}
  <div class="row mb-3">
    <div class="col-3">
      {{ form.jira_cc_id.label(class="form-label") }} {{
      form.jira_cc_id(class="form-control") }}
    </div>
    <div class="col-9">
      {{ form.jira_cc_url.label(class="form-label") }} {{
      form.jira_cc_url(class="form-control") }}
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-3">
      {{ form.jira_csm1_id.label(class="form-label") }} {{
      form.jira_csm1_id(class="form-control") }}
    </div>
    <div class="col-9">
      {{ form.jira_csm1_url.label(class="form-label") }} {{
      form.jira_csm1_url(class="form-control") }}
    </div>
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock content %}

web/templates/requests/status_updates.html
{% extends 'base.html' %} {% block content %}
<h1>Connection Status Update</h1>
<p>Update the status of the connection request.</p>
<form method="post">
  {{ form.hidden_tag() }}
  <div class="row mb-3">
    <div class="col">
      {{ form.working_status.label(class="form-label")}} {{
      form.working_status(class="form-select") }}
    </div>
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock content %}

web/templates/requests/view_request.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>View Connection Request</h1>
  <!-- Actions - Start -->
  <div class="row">
    <div class="button-group">
      <a
        href="{{ url_for('requests.edit_request', request_id=connection_request.id) }}"
        ><button>Edit Connection Request</button></a
      >
      <a
        href="{{ url_for('requests.status_updates', request_id=connection_request.id) }}"
      >
        <button>Edit Request Status</button>
      </a>
      <a
        href="{{ url_for('requests.jira_ticket_updates', request_id=connection_request.id) }}"
      >
        <button>Edit Jira Tickets</button>
      </a>
      <a
        href="{{ url_for('requests.request_pdf', request_id=connection_request.id) }}"
        ><button>Generate Request PDF</button></a
      >
    </div>
  </div>
  <!-- Actions - End -->
  <!-- Status - Start -->
  <h3>Connection Request Status</h3>
  <div class="row">
    <div class="three columns">
      <h5>Status</h5>
      <p>{{ connection_request.working_status }}</p>
    </div>
    <div class="three columns">
      <h5>CC Jira Ticket</h5>
      {% if connection_request.jira_cc_id %}
      <a
        href="{{ connection_request.jira_cc_url}}"
        target="_blank"
        rel="noopener noreferrer"
        >CC-{{ connection_request.jira_cc_id }}</a
      >
      {% endif %}
    </div>
    <div class="three columns">
      <h5>CSM1 Jira Ticket</h5>
      {% if connection_request.jira_csm1_id %}
      <a
        href="{{ connection_request.jira_csm1_url}}"
        target="_blank"
        rel="noopener noreferrer"
        >CSM1-{{ connection_request.jira_csm1_id }}</a
      >
      {% endif %}
    </div>
  </div>
  <!-- Status - End -->
  <!-- Health App Matching - Start -->
  <h5>Health App Matching</h5>
  <button id="matchButton" data-request-id="{{ connection_request.id }}">
    Re-check Health App Match
  </button>
  <div class="row">
    <div class="six columns">
      <p>CARIN - Company: <span id="carinCompanyMatch"></span></p>
      <p>CARIN - App Name: <span id="carinAppMatch"></span></p>
    </div>
    <div class="six columns">
      <p>
        Medicare Blue Button - Company:
        <span id="medicareCompanyMatch"></span>
      </p>
      <p>
        Medicare Blue Button - App Name:
        <span id="medicareAppMatch"></span>
      </p>
    </div>
  </div>
  <div class="row">
    <p>Affiliate match probability: <span id="matchProbability">?</span>%</p>
  </div>
  <!-- Connect Request Information - Start -->
  <h3>Connect Request Information</h3>
  <div class="row">
    <div class="six columns">
      <h5>Health Plan</h5>
      <p>{{ connection_request.name }} ({{ connection_request.hp_id }})</p>
    </div>
    <div class="six columns">
      <h5>APIs Requested</h5>
      <div>
        {% if connection_request.fhir_patient_access_api %}
        <p><i class="fas fa-bolt"></i><span> Patient Access API</span></p>
        {% endif %} {% if connection_request.fhir_provider_directory_api %}
        <p><i class="fas fa-bolt"></i><span> Provider Directory API</span></p>
        {% endif %} {% if connection_request.fhir_drug_formulary_api %}
        <p><i class="fas fa-bolt"></i><span> Drug Formulary API</span></p>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="six columns">
      <h5>App Name</h5>
      <p>{{ connection_request.app_name }}</p>
      <a
        href="{{ connection_request.app_link }}"
        target="_blank"
        rel="noopener noreferrer"
        >{{ connection_request.app_link }}</a
      >
    </div>
    <div class="six columns">
      <h5>App Description</h5>
      <p>{{ connection_request.app_description }}</p>
    </div>
  </div>
  <div class="row">
    <div class="six columns">
      <h5>Requestor Information</h5>
      <p>
        {{ connection_request.firstname }} {{ connection_request.lastname }}
      </p>
      <p>{{ connection_request.email }}</p>
      <p>{{ connection_request.phone_number }}</p>
    </div>
    <div class="six columns">
      <h5>Company Information</h5>
      <p>{{ connection_request.company }}</p>
      <a
        href="{{ connection_request.company_website}}"
        target="_blank"
        rel="noopener noreferrer"
        >{{ connection_request.company_website }}</a
      >
    </div>
  </div>
  <div class="row">
    {% if connection_request.carin_link %}
    <div class="four columns">
      <h5>CARIN App</h5>
      <a
        href="{{ connection_request.carin_link }}"
        target="_blank"
        rel="noopener noreferrer"
        >{{ connection_request.carin_link }}</a
      >
    </div>
    {% endif %} {% if connection_request.medicare_link %}
    <div class="four columns">
      <h5>Medicare Blue Button App</h5>
      <a
        href="{{ connection_request.medicare_link }}"
        target="_blank"
        rel="noopener noreferrer"
        >{{ connection_request.medicare_link }}</a
      >
    </div>
    {% endif %} {% if connection_request.caqh_link %}
    <div class="four columns">
      <h5>CAQH App</h5>
      <a
        href="{{ connection_request.caqh_link }}"
        target="_blank"
        rel="noopener noreferrer"
        >{{ connection_request.caqh_link }}</a
      >
    </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="u-full-width">
      <h5>Request Date</h5>
      <p
        class="timestamp"
        data-utc="{{ connection_request.created_date.isoformat() }}Z"
      ></p>
    </div>
  </div>
  <!-- Connect Request Information - End -->
</div>

<script>
  // Function to update match result
  function updateMatchResult(element, isMatch) {
    element.innerHTML = isMatch
      ? '<i class="fas fa-bolt"></i><span> Match</span>'
      : '<i class="fas fa-circle-xmark"></i><span> No match</span>';
  }

  // Function to fetch match info
  function fetchMatchInfo(requestId) {
    fetch(`/healthapp_match/${requestId}`, {
      method: "GET",
    })
      .then((response) => response.json())
      .then((data) => {
        // Update the HTML content based on the returned data
        updateMatchResult(carinCompanyMatch, data.carin_company_match);
        updateMatchResult(medicareCompanyMatch, data.medicare_company_match);
        updateMatchResult(carinAppMatch, data.carin_app_match);
        updateMatchResult(medicareAppMatch, data.medicare_app_match);
        matchProbability.textContent = data.match_probability;
      })
      .catch((error) => {
        console.error("An error occurred:", error);
      });
  }

  // Fetch the health app match info when the page loads
  document.addEventListener("DOMContentLoaded", function () {
    const carinCompanyMatch = document.getElementById("carinCompanyMatch");
    const medicareCompanyMatch = document.getElementById(
      "medicareCompanyMatch"
    );
    const carinAppMatch = document.getElementById("carinAppMatch");
    const medicareAppMatch = document.getElementById("medicareAppMatch");
    const matchProbability = document.getElementById("matchProbability");

    const requestId = matchButton.getAttribute("data-request-id");
    fetchMatchInfo(requestId);
  });

  // Fetch the health app match info when the user clicks the button
  const matchButton = document.getElementById("matchButton");
  matchButton.addEventListener("click", function () {
    const requestId = matchButton.getAttribute("data-request-id");
    fetchMatchInfo(requestId);
  });
</script>
<script src=" {{ url_for('static', filename='js/convert_timezone.js') }}"></script>
{% endblock content %}