web/settings/models.py
"""
Settings database models for the application.
"""
# Imports
from datetime import datetime
from app import db


# Model - HealthTrio Health Plans
class HealthPlan(db.Model):
    """Health Plans Model"""

    __tablename__ = "health_plans"

    # IDs
    id = db.Column(db.Integer, primary_key=True)
    # Health Plan Information
    name = db.Column(db.String(255), nullable=False)
    hp_id = db.Column(db.String(255), nullable=False)
    # Status
    status = db.Column(db.String(10), default="ACTIVE")
    # Timestamps
    created_date = db.Column(db.DateTime, nullable=False,
                             default=datetime.utcnow)
    updated_date = db.Column(db.DateTime)
    # Updatestamps
    created_by = db.Column(db.Integer, db.ForeignKey("users.id"))
    updated_by = db.Column(db.Integer, db.ForeignKey("users.id"))

web/forms/settings_forms.py
"""
Settings > forms.py
This file contains the forms for the Settings Blueprint.
"""

# Imports
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, StringField
from wtforms.validators import DataRequired


# Form - Change User's Role
class ChangeRoleForm(FlaskForm):
    """Change user's role form"""

    role = SelectField('Role', choices=[('admin', 'Admin'),
                                        ('user', 'User')])
    submit = SubmitField('Submit')


# Form - Change User's Status
class ChangeStatusForm(FlaskForm):
    """Change user's status form"""

    status = SelectField('Status', choices=[('ACTIVE', 'Active'),
                                            ('INACTIVE', 'Inactive')])
    submit = SubmitField('Submit')


# Form - Health Plans
class HealthPlanForm(FlaskForm):
    """Health Plans form"""

    name = StringField('Name', validators=[DataRequired()])
    hp_id = StringField('Health Plan ID', validators=[DataRequired()])
    status = SelectField('Status', choices=[('ACTIVE', 'Active'),
                                            ('INACTIVE', 'Inactive')])
    submit = SubmitField('Submit')

web/settings/forms.py
"""
Settings > forms.py
This file contains the forms for the Settings Blueprint.
"""

# Imports
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, StringField
from wtforms.validators import DataRequired


# Form - Change User's Role
class ChangeRoleForm(FlaskForm):
    """Change user's role form"""

    role = SelectField('Role', choices=[('admin', 'Admin'),
                                        ('user', 'User')])
    submit = SubmitField('Submit')


# Form - Change User's Status
class ChangeStatusForm(FlaskForm):
    """Change user's status form"""

    status = SelectField('Status', choices=[('ACTIVE', 'Active'),
                                            ('INACTIVE', 'Inactive')])
    submit = SubmitField('Submit')


# Form - Health Plans
class HealthPlanForm(FlaskForm):
    """Health Plans form"""

    name = StringField('Name', validators=[DataRequired()])
    hp_id = StringField('Health Plan ID', validators=[DataRequired()])
    status = SelectField('Status', choices=[('ACTIVE', 'Active'),
                                            ('INACTIVE', 'Inactive')])
    submit = SubmitField('Submit')

web/settings/views.py
"""
Settings > views.py
Routes and functions to manage application settings.
"""
# Imports
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required
from forms.settings_forms import ChangeRoleForm, ChangeStatusForm, HealthPlanForm
from decorators.decorators import admin_required
from sqlalchemy import or_
from app import db
from models.settings_models import HealthPlan
from models.users_models import User


# Blueprint Configuration
settings_bp = Blueprint('settings', __name__)


# Route - Settings Landing Page
@settings_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    """Settings landing page"""

    return render_template('settings/settings.html',
                           title='Settings')


# Route - Settings > Manage Users
@settings_bp.route('/settings/manage-users',
                   methods=['GET', 'POST'])
@admin_required
@login_required
def manage_users():
    """Manage users page"""

    users = User.query.all()

    return render_template('settings/manage-users.html',
                           title='Manage Users',
                           users=users)


# Route - Settings > Manage Users > Change Role
@settings_bp.route('/settings/manage-users/change-role/<int:user_id>',
                   methods=['GET', 'POST'])
@admin_required
@login_required
def change_role(user_id):
    """Change user role page"""

    user = User.query.get_or_404(user_id)

    form = ChangeRoleForm()

    if request.method == 'GET':
        form.role.data = user.role

    if form.validate_on_submit():
        user.role = form.role.data
        db.session.commit()

        return redirect(url_for('settings.manage_users'))

    return render_template('settings/change-role.html',
                           title='Change Role',
                           form=form,
                           user=user)


# Route - Settings > Manage Users > Change Status
@settings_bp.route('/settings/manage-users/change-status/<int:user_id>',
                   methods=['GET', 'POST'])
@admin_required
@login_required
def change_status(user_id):
    """Change user status page"""

    user = User.query.get_or_404(user_id)

    form = ChangeStatusForm()

    if request.method == 'GET':
        form.status.data = user.status

    if form.validate_on_submit():
        user.status = form.status.data
        db.session.commit()

        return redirect(url_for('settings.manage_users'))

    return render_template('settings/change-status.html',
                           title='Change Status',
                           form=form,
                           user=user)


# Settings - Manage Health Plans
@settings_bp.route('/settings/manage-health-plans',
                   methods=['GET', 'POST'])
@login_required
def manage_health_plans():
    """Manage health plans page"""

    health_plans = HealthPlan.query.all()

    return render_template('settings/manage-health-plans.html',
                           title='Manage Health Plans',
                           health_plans=health_plans)


# Settings - Manage Health Plans > Add Health Plan
@settings_bp.route('/settings/manage-health-plans/add-health-plan',
                   methods=['GET', 'POST'])
@login_required
def add_health_plan():
    """Add health plan page"""

    form = HealthPlanForm()

    if form.validate_on_submit():
        # Check if health plan already exists via name or health plan ID
        health_plan = HealthPlan.query.filter(
            or_(HealthPlan.name == form.name.data,
                HealthPlan.hp_id == form.hp_id.data)).first()
        if health_plan:
            flash('Health plan already exists.', 'danger')

        # Add to the database
        health_plan = HealthPlan(
            name=form.name.data,
            hp_id=form.hp_id.data,
            status=form.status.data,)
        db.session.add(health_plan)
        db.session.commit()

        flash('Health Plan added successfully.', 'success')
        return redirect(url_for('settings.manage_health_plans'))

    return render_template('settings/add-edit-health-plan.html',
                           title='Add Health Plan',
                           form=form)


# Settings - Manage Health Plans > Edit Health Plan
@settings_bp.route(
    '/settings/manage-health-plans/edit-health-plan/<int:health_plan_id>',
    methods=['GET', 'POST'])
@login_required
def edit_health_plan(health_plan_id):
    """Edit health plan page"""

    health_plan = HealthPlan.query.get_or_404(health_plan_id)

    form = HealthPlanForm()

    if request.method == 'GET':
        form.name.data = health_plan.name
        form.hp_id.data = health_plan.hp_id
        form.status.data = health_plan.status

    if form.validate_on_submit():
        # Update the database
        health_plan.name = form.name.data
        health_plan.hp_id = form.hp_id.data
        health_plan.status = form.status.data
        db.session.commit()

        flash('Health Plan updated successfully.', 'success')
        return redirect(url_for('settings.manage_health_plans'))

    return render_template('settings/add-edit-health-plan.html',
                           title='Edit Health Plan',
                           form=form,
                           health_plan=health_plan)

web/views/settings_views.py
"""
Settings > views.py
Routes and functions to manage application settings.
"""
# Imports
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required
from forms.settings_forms import ChangeRoleForm, ChangeStatusForm, HealthPlanForm
from decorators.decorators import admin_required
from sqlalchemy import or_
from app import db
from models.settings_models import HealthPlan
from models.users_models import User


# Blueprint Configuration
settings_bp = Blueprint('settings', __name__)


# Route - Settings Landing Page
@settings_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    """Settings landing page"""

    return render_template('settings/settings.html',
                           title='Settings')


# Route - Settings > Manage Users
@settings_bp.route('/settings/manage-users',
                   methods=['GET', 'POST'])
@admin_required
@login_required
def manage_users():
    """Manage users page"""

    users = User.query.all()

    return render_template('settings/manage-users.html',
                           title='Manage Users',
                           users=users)


# Route - Settings > Manage Users > Change Role
@settings_bp.route('/settings/manage-users/change-role/<int:user_id>',
                   methods=['GET', 'POST'])
@admin_required
@login_required
def change_role(user_id):
    """Change user role page"""

    user = User.query.get_or_404(user_id)

    form = ChangeRoleForm()

    if request.method == 'GET':
        form.role.data = user.role

    if form.validate_on_submit():
        user.role = form.role.data
        db.session.commit()

        return redirect(url_for('settings.manage_users'))

    return render_template('settings/change-role.html',
                           title='Change Role',
                           form=form,
                           user=user)


# Route - Settings > Manage Users > Change Status
@settings_bp.route('/settings/manage-users/change-status/<int:user_id>',
                   methods=['GET', 'POST'])
@admin_required
@login_required
def change_status(user_id):
    """Change user status page"""

    user = User.query.get_or_404(user_id)

    form = ChangeStatusForm()

    if request.method == 'GET':
        form.status.data = user.status

    if form.validate_on_submit():
        user.status = form.status.data
        db.session.commit()

        return redirect(url_for('settings.manage_users'))

    return render_template('settings/change-status.html',
                           title='Change Status',
                           form=form,
                           user=user)


# Settings - Manage Health Plans
@settings_bp.route('/settings/manage-health-plans',
                   methods=['GET', 'POST'])
@login_required
def manage_health_plans():
    """Manage health plans page"""

    health_plans = HealthPlan.query.all()

    return render_template('settings/manage-health-plans.html',
                           title='Manage Health Plans',
                           health_plans=health_plans)


# Settings - Manage Health Plans > Add Health Plan
@settings_bp.route('/settings/manage-health-plans/add-health-plan',
                   methods=['GET', 'POST'])
@login_required
def add_health_plan():
    """Add health plan page"""

    form = HealthPlanForm()

    if form.validate_on_submit():
        # Check if health plan already exists via name or health plan ID
        health_plan = HealthPlan.query.filter(
            or_(HealthPlan.name == form.name.data,
                HealthPlan.hp_id == form.hp_id.data)).first()
        if health_plan:
            flash('Health plan already exists.', 'danger')

        # Add to the database
        health_plan = HealthPlan(
            name=form.name.data,
            hp_id=form.hp_id.data,
            status=form.status.data,)
        db.session.add(health_plan)
        db.session.commit()

        flash('Health Plan added successfully.', 'success')
        return redirect(url_for('settings.manage_health_plans'))

    return render_template('settings/add-edit-health-plan.html',
                           title='Add Health Plan',
                           form=form)


# Settings - Manage Health Plans > Edit Health Plan
@settings_bp.route(
    '/settings/manage-health-plans/edit-health-plan/<int:health_plan_id>',
    methods=['GET', 'POST'])
@login_required
def edit_health_plan(health_plan_id):
    """Edit health plan page"""

    health_plan = HealthPlan.query.get_or_404(health_plan_id)

    form = HealthPlanForm()

    if request.method == 'GET':
        form.name.data = health_plan.name
        form.hp_id.data = health_plan.hp_id
        form.status.data = health_plan.status

    if form.validate_on_submit():
        # Update the database
        health_plan.name = form.name.data
        health_plan.hp_id = form.hp_id.data
        health_plan.status = form.status.data
        db.session.commit()

        flash('Health Plan updated successfully.', 'success')
        return redirect(url_for('settings.manage_health_plans'))

    return render_template('settings/add-edit-health-plan.html',
                           title='Edit Health Plan',
                           form=form,
                           health_plan=health_plan)

web/templates/settings/add-edit-health-plan.html
{% extends 'base.html' %} {% block content %}
<h1>Add/Edit Health Plan</h1>
<form method="post">
  {{ form.hidden_tag() }}
  <div class="row mb-3">
    <div class="col">
      {{ form.name.label(class="form-label") }} {{
      form.name(class="form-control") }}
    </div>
    <div class="col">
      {{ form.hp_id.label(class="form-label") }} {{
      form.hp_id(class="form-control") }}
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">
      {{ form.status.label(class="form-label") }} {{
      form.status(class="form-select") }}
    </div>
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock content %}

web/templates/settings/change-role.html
{% extends 'base.html' %} {% block content %}
<h1>Change User's Role</h1>
<form method="post">
  {{ form.hidden_tag() }}
  <div class="row mb-3">
    {{ form.role.label(class="form-label") }} {{ form.role(class="form-select")
    }}
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock content %}

web/templates/settings/change-status.html
{% extends 'base.html' %} {% block content %}
<h1>Change User's Status</h1>
<form method="post">
  {{ form.hidden_tag() }}
  <div class="row mb-3">
    {{ form.status.label(class="form-label") }} {{
    form.status(class="form-select") }}
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock content %}

web/templates/settings/manage-health-plans.html
{% extends 'base.html' %} {% block content %}
<h1>Manage Health Plans</h1>
<div class="row mb-3">
  <a href="{{ url_for('settings.add_health_plan') }}" class="btn btn-primary"
    >Add Health Plan</a
  >
</div>
<div class="row mb-3">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>HealthTrio ID</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% if health_plans %} {% for plan in health_plans %}
      <tr>
        <td>{{ plan.name }}</td>
        <td>{{ plan.hp_id }}</td>
        <td>{{ plan.status }}</td>
        <td>
          <a
            href="{{ url_for('settings.edit_health_plan', health_plan_id=plan.id) }}"
            class="btn btn-primary"
            >Edit</a
          >
        </td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td colspan="4">No health plans found.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
</div>
{% endblock content %}

web/templates/settings/manage-users.html
{% extends 'base.html' %} {% block content %}
<h1>Infero Users</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
    <tr>
      <td>{{ user.email }}</td>
      <td>{{ user.role }}</td>
      <td>{{ user.status }}</td>
      <td>
        <div class="btn-group">
          <a
            href="{{ url_for('settings.change_role', user_id=user.id) }}"
            class="btn btn-primary"
            >Change Role</a
          >
          <a
            href="{{ url_for('settings.change_status', user_id=user.id) }}"
            class="btn btn-primary"
            >Update Status</a
          >
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

web/templates/settings/settings.html
{% extends 'base.html' %} {% block content %}
<h1>Settings</h1>
<p>Change the settings for the Inferno application here.</p>
<div class="row mb-3">
  <div class="col">
    <h3>Users</h3>
    <p>Manage users here.</p>
    <a href="{{ url_for('settings.manage_users') }}" class="btn btn-primary"
      >Manage Users</a
    >
  </div>
  <div class="col">
    <h3>Health Plans</h3>
    <p>Manage health plans here.</p>
    <a
      href="{{ url_for('settings.manage_health_plans') }}"
      class="btn btn-primary"
      >Manage Health Plans</a
    >
  </div>
</div>
{% endblock content %}